Add test creating two content filter topics with the same topic name
eProsima/rclcpp pull request #1
Opened 2024-05-29 09:02 UTC by Mario-DL

This PR adds the proper test in `rclcpp` that checks for a successful creation of two content filter topics for the same topic name.
* Related PR https://github.com/eProsima/rmw_fastrtps/pull/29

2024-05-29 09:33 UTC, MiguelCompany requested changes

2024-05-29 09:33 UTC, MiguelCompany commented on rclcpp/test/rclcpp/test_subscription_content_filter.cpp
> +  // Create anothe content filter
```suggestion
  // Create another content filter
```

2024-05-29 09:42 UTC, MiguelCompany approved these changes

2024-05-30 10:10 UTC, Mario-DL commented
Closed in favor of https://github.com/ros2/rclcpp/pull/2546

2024-05-30 10:10 UTC, closed without merging